# Generated by Django 5.1.15 on 2026-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_cancel_and_format'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='downloadjob',
            new_name='jobs_downlo_status_30f5b9_idx',
            old_name='jobs_downlo_status_6f3c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='downloadjob',
            new_name='jobs_downlo_user_id_9a0b99_idx',
            old_name='jobs_downlo_user_id_status_idx',
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='clip_end_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='clip_start_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='seconds', null=True),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
